CREATE TABLE IF NOT EXISTS address
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id   BIGINT NOT NULL,
    type          VARCHAR(50),
    lga           VARCHAR(50),
    town          VARCHAR(50),
    address_line  VARCHAR(200),
    state         VARCHAR(50),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
