CREATE TABLE customer
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    password      VARCHAR(255) NOT NULL,
    firstname     VARCHAR(255) NOT NULL,
    lastname      VARCHAR(255)NOT NULL,
    email_address VARCHAR(255) NOT NULL UNIQUE,
    external_id VARCHAR(255) ,
    phone_number  VARCHAR(20) NOT NULL UNIQUE,
    kyc_tier  VARCHAR(20),
    account_id  VARCHAR(20),
    referral_code VARCHAR(50),
    bvn VARCHAR(11),
    nin VARCHAR(11),
    is_Active       BOOLEAN NOT NULL DEFAULT FALSE,
    user_type     VARCHAR(50) NOT NULL,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);
CREATE SEQUENCE customer_seq START WITH 1 INCREMENT BY 1;
