CREATE TABLE payment_order
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount DECIMAL(10, 2),
    currency VARCHAR(3),
    status VARCHAR(30),
    customer_id BIGINT NOT NULL,
    reference VARCHAR(100),
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);
CREATE SEQUENCE payment_order_seq START WITH 1 INCREMENT BY 1;
